#---- Bioconda config ----
name: buscophylo
channels:
  - bioconda
  - conda-forge
dependencies:
  - python>=3.8
  - blast
  - hmmer
  - busco=3
  - mafft
  #- augustus
  #- scipy
  #- xmltodict
  #- ete3
