#---- Ğ¡onda config ----
name: buscophylo
channels:
  - bioconda
  - conda-forge
dependencies:
  - python>=3.8
  - biopython>=1.70
  - busco=5.2.2
  - samtools>=1.10
  - mafft>=7.4
  - prank
#  - trimAl=1.2rev59
#  - iqtree=2.1.3
#  - mrbayes=v3.2.7